#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source OpenFOAM functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)
numProcessors=$(getNumberOfProcessors)

blockMesh > log.blockMesh 2>&1
checkMesh > log.checkMesh 2>&1
setFields > log.setFields 2>&1
decomposePar -force > log.decomposePar 2>&1

foamCloneCase . ./temp > log.foamCloneCase 2>&1
postProcess -funcs '(writeCellCentres writeCellVolumes)' -case ./temp > log.postProcess 2>&1

mpirun -np $numProcessors $application -parallel > log.mpirun 2>&1
reconstructPar > log.reconstructPar 2>&1